import {MSJ_VALIDANDO, MSJ_CODE_NOTFOUND, MSJ_NODATA_REQUIRED, MSJ_TITULO_COD_NOVAL} from './Mensajes/MsjValidacionesLiga'

export {
    MSJ_VALIDANDO, MSJ_CODE_NOTFOUND, MSJ_NODATA_REQUIRED, MSJ_TITULO_COD_NOVAL
}